server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api  #添加路由前缀
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000 #熔断超时时长：7000ms
ribbon:
  connetTimeout: 500  # ribbon连接超时时长
  readTimeout: 5000   # ribbon读取超时时长
  maxAutoRetries: 0   # 当前服务重试次数
  maxAutoRetriesNextServer: 0 #切换服务重试次数


